name: Metrics
on:
  # Запускается при каждом пуше в главную ветку
  push:
    branches: ["main"]
  # Запускается по расписанию (каждые 4 часа)
  schedule:
    - cron: "0 */4 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Токен
          token: ${{ secrets.METRICS_TOKEN }}
          # Имя пользователя
          user: Ddarkover
          # Используемые плагины
          plugin_lines: yes
          plugin_languages: yes
          plugin_introduction: yes
          # Настройки для плагинов
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming, markup
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: programming, markup
          plugin_languages_recent_days: 14
          plugin_languages_sections: most-used
          # Файл, в который будет записан результат
          filename: metrics.svg
          # Автоматически коммитить результат
          committer_branch: main
